name: 'Job Validation'
description: 'Greet someone and record the time'
inputs:
  command:
    description: 'command from PR comment'
    required: true
outputs:
  action:
    description: 'The job from input command'
  flavors:
    description: 'Build flavors'
runs:
  using: 'node16'
  main: 'dist/index.js'