name: Experiment

on:
  issue_comment:
    types:
      - created
      
permissions:
  contents: read
  pull-requests: read

jobs:

  parsing:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && ( startsWith(github.event.comment.body, '/test') || startsWith(github.event.comment.body, '/build') ) }}
    outputs:
      action: ${{ steps.get-output.outputs.action }}
      build_options: ${{ steps.get-output.outputs.build_options }}
    steps: 
      - name: Parse command
        id: parse-input
        uses: syaiful-aa/actions-experiment/command-parser@v3.0.1
        # uses: ./github/actions/command-parser
        with:
          command: ${{ github.event.comment.body }}
      - name: Get job action and build options
        id: get-output
        run: | 
          echo "action=${{ toJson(steps.parse-input.outputs.action) }}" >> $GITHUB_OUTPUT
          echo "build_options=$(jq -r -c . <<< "${{ toJson(steps.parse-input.outputs.build_options) }}")" >> $GITHUB_OUTPUT

  testing:
    needs: parsing
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "action: ${{ needs.parsing.outputs.action }}"

  deploy:
    needs: [parsing, testing]
    runs-on: ubuntu-latest
    if: ${{ needs.parsing.outputs.action == '/build' && contains(needs.testing.result , 'success') }}
    strategy:
      matrix:
        build_options: ${{ fromJSON(needs.parsing.outputs.build_options) }}
    env:
      artifact_type: ${{ matrix.build_options.artifact }}
      flavor: ${{ matrix.build_options.flavor }}
      build_mode: ${{ matrix.build_options.mode }}
      build_option: "${{ matrix.build_options.artifact }} --flavor ${{ matrix.build_options.flavor }} --${{ matrix.build_options.mode }}"
    steps:
      - name: build
        run: |
          echo "$artifact_type $flavor $build_mode"
          echo $build_option
      - name: Build Apk ${{ env.flavor }} --${{ env.build_mode }}
        if: ${{ env.artifact_type == 'apk'}}
        run: |
          echo "build $artifact_type $flavor $build_mode" >> "$artifact_type"
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: "${{ env.artifact_type }} ${{ env.flavor }} ${{ env.build_mode }}"
            path: ${{ env.artifact_type }}
          
  job_completion:
    needs: [parsing, testing, deploy]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Check Completion
        run: |
          if [[ ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/test') }} ]]; then
            if [[ ${{ needs.testing.result == 'success' }} ]]
              exit 0
            fi
          fi
          if [[ ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/build') }} ]]; then
            if [[ ${{ needs.testing.result == 'success' && needs.deploy.result == 'success' }} ]]; then
              exit 0
            fi
          fi
          exit 1
      - name: Send context
        run: |
          echo "send context"


