name: Scheduled Job

on:
  workflow_dispatch:
  schedule:
    - cron: '{{0 9 * * Sun [ $(expr $(date +%W) % 2) -eq 1 ] && /path/to/command}}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Add your job steps here
    - name: Example Job Step
      run: echo "This is an example job step"
