name: Scheduled Job

on:
  workflow_dispatch:
  schedule:
    - cron: '${{ github.event.schedule }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Add your job steps here
    - name: Example Job Step
      run: echo "This is an example job step"
