name: Experiment

on:
  issue_comment:
    types:
      - created
      
permissions:
  contents: read
  pull-requests: read

jobs:
  job-validation:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && (startsWith(github.event.comment.body, '/build') || startsWith(github.event.comment.body, '/test')) }} 
    outputs:
      arguments: ${{ steps.check-command.outputs.arguments }}
      arguments2: ${{ steps.check-command.outputs.arguments2 }}

    steps:
      - name: Check command from input
        id: check-command
        run: |
          rawInput="${{ github.event.comment.body }}"
          input=${rawInput///""}

          IFS=" " read -ra inputSplitted <<< "$input"
          action=${inputSplitted[0]}
          options=${input/$action/""}

          echo $action
          echo $options

          IFS="," read -ra optionsSplitted <<< "$options"
          for option in "${optionsSplitted[@]}"; do
            echo $option
          done

          echo "arguments=${optionsSplitted[@]}" >> "$GITHUB_OUTPUT"
          echo "arguments2=$optionsSplitted" >> "$GITHUB_OUTPUT"

          echo "finish"


      - name: Check output
        id: check-output
        run: |
          echo "start"
          echo "output: ${{ steps.check-command.outputs.arguments }}"
          echo "output: ${{ steps.check-command.outputs.arguments2 }}"
          echo "output: ${{ fromJSON(steps.check-command.outputs.arguments) }}"
          echo "output: ${{ fromJSON(steps.check-command.outputs.arguments2) }}"




      