name: Flow test

on:
  issue_comment:
    types:
      - created
      
permissions:
  contents: read
  pull-requests: read

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run-flow') }} 
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      output_inside: ${{ steps.pass.outputs.test }}
    steps:
      - name: get pull request metadata
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: setup branch 
        uses: actions/checkout@v3
        with:
          ref: 'test/cicd'
      - name: get PR details
        uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: get-pr-details
        with:
          github-token: ${{ github.token }}
          sha: ${{ steps.comment-branch.outputs.head_sha }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: pass
        id: pass
        env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: |
          echo ${{ steps.get-pr-details.outputs }}
          echo ${{ steps.comment-branch.outputs }}
          echo $GITHUB_OUTPUT
          echo "$OUTPUT1 $OUTPUT2" 
          sh scripts/flow.sh morning
          FROM_JS=$(node scripts/flow.js)
          echo $FROM_JS
          echo "fromJs=$FROM_JS" >> "$GITHUB_OUTPUT"
      - name: receive
        run: | 
          echo ${{ steps.pass.outputs.test }}
          echo ${{ steps.pass.outputs.message }}
          echo ${{ steps.pass.outputs.fromJs }}
          echo $ANDROID_HOME
