name: HIT

on:
  workflow_dispatch:
    inputs:
      sha:
        type: string
        description: sha
      is_success:
        type: boolean
        description: is success
      check_context:
        type: string
        description: check context


jobs:

  hit:
    runs-on: ubuntu-latest
    steps: 
      - name: Job Completion
        uses: syaiful-aa/actions-experiment/send-check-status@v3.1.1
        with:
          repository: ${{ github.repository }}
          sha: ${{ inputs.sha }}
          run_id: 5353983372
          token: ${{ secrets.GITHUB_TOKEN }}
          is_success: ${{ inputs.is_success }}
          check_context: ${{ inputs.check_context }}