name: Android Release

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{github.event.issue.pull_request && github.event.comment.body == '/build'}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle' 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.8"
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Start release build
        run: flutter build appbundle
      - name: Save aab artifact
        uses: actions/upload-artifact@v1
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab