name: Ondemand Build

on:
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        description: Flavor
        options: 
        - Dev
        - Staging
        - Production
      is-debug:
        type: boolean
        description: Debug mode
      artifact:
        type: choice
        description: Artifact Type
        options: 
        - Apk
        - Appbundle

jobs:
  config:
    runs-on: ubuntu-latest

    steps:
    - name: Entry point
      run: |
        echo "Build artifact with these configuration: ${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
        echo "Flavor:  ${{ github.event.inputs.flavor }}"
        echo "Is debug mode?:  ${{ github.event.inputs.is-debug }}"
        echo "Artifact Type:  ${{ github.event.inputs.artifact }}"
        echo "Metadata: ${{ github.ref }} | ${{ github.ref_name }} | ${{ github.sha }}"
    - name: setup branch 
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
      run: |
        pwd
        ls

