name: Run Danger

on:
  pull_request:
    types: [ready_for_review, edited, synchronize, reopened]

jobs:
  check_danger:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: get pull request metadata
        id: pr-metadata
        uses: xt0rted/pull-request-comment-branch@v1

      - name: validate branch
        id: validate-branch
        run: echo "is_skipped=${{ startsWith(github.head_ref, 'release/') && github.base_ref == 'main' }}" >> $GITHUB_OUTPUT

      - name: check validation
        run: |
          echo "is skipped: ${{ steps.validate-branch.outputs.is_skipped == true }}"

      - name: Checkout code
        if: steps.validate-branch.outputs.is_skipped == 'false'
        uses: actions/checkout@v3

      - name: Setup Node.js
        if: steps.validate-branch.outputs.is_skipped == 'false'
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Run danger
        if: steps.validate-branch.outputs.is_skipped == 'false'
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
